"""Agent reports tools — list and read agent team reports."""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

from mcp_server.server import mcp

logger = logging.getLogger(__name__)

_TEAM_DIRS = [
    "agents",
    "data_team",
    "product_team",
    "ops_team",
    "finance_team",
    "gtm_team",
    "agents/chief_of_staff",
]


def _get_project_root() -> str:
    current = Path(__file__).resolve()
    for parent in current.parents:
        if (parent / "requirements.txt").exists():
            return str(parent)
    return os.getcwd()


@mcp.tool()
def list_reports() -> dict[str, Any]:
    """List latest agent report files across all 6 teams + CoS.

    Reports are JSON/markdown files generated by agent orchestrators.
    Use read_report to view a specific report's content.
    """
    # Try Redis first
    try:
        from agents.shared.report_store import list_reports_from_redis

        redis_reports = list_reports_from_redis()
        if redis_reports:
            return {
                "reports": redis_reports,
                "count": len(redis_reports),
                "source": "redis",
            }
    except Exception:
        pass

    # Filesystem fallback
    root = Path(_get_project_root())
    reports = []

    for team_dir in _TEAM_DIRS:
        report_path = root / team_dir / "reports"
        if not report_path.is_dir():
            continue

        for f in sorted(report_path.iterdir()):
            if f.is_file() and f.suffix in (".json", ".md", ".txt"):
                reports.append(
                    {
                        "team": team_dir,
                        "filename": f.name,
                        "size_bytes": f.stat().st_size,
                        "modified": f.stat().st_mtime,
                    }
                )

    return {"reports": reports, "count": len(reports)}


@mcp.tool()
def read_report(team: str, filename: str) -> dict[str, Any]:
    """Read a specific agent report by team and filename.

    Use list_reports first to see available reports.
    Team values: agents, data_team, product_team, ops_team,
    finance_team, gtm_team, agents/chief_of_staff.
    """
    if ".." in filename or "/" in filename or "\\" in filename:
        return {"error": "Invalid filename — path traversal not allowed"}

    # Try Redis first
    try:
        from agents.shared.report_store import read_report_from_redis

        result = read_report_from_redis(team, filename)
        if result:
            return result
    except Exception:
        pass

    # Filesystem fallback
    if team not in _TEAM_DIRS:
        return {"error": f"Unknown team: {team}. Valid: {', '.join(_TEAM_DIRS)}"}

    root = Path(_get_project_root())
    report_path = root / team / "reports" / filename

    if not report_path.is_file():
        return {"error": f"Report not found: {team}/reports/{filename}"}

    try:
        content = report_path.read_text(encoding="utf-8")
        return {
            "team": team,
            "filename": filename,
            "content": content,
            "size_bytes": len(content),
        }
    except Exception as exc:
        return {"error": f"Failed to read report: {exc}"}
